os:
  editPreset: 'nvim'
notARepository: 'quit'
git:
  paging:
    colorArg: always
  #   pager: delta --dark --paging=never
  commitPrefix:
    - pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '[$1] '
gui:
  nerdFontsVersion: "3"
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6da95" # Green
      - bold
    inactiveBorderColor:
      - "#cad3f5" # Text
    optionsTextColor:
      - "#8aadf4" # Blue
    selectedLineBgColor:
      - "#363a4f" # Surface0
    selectedRangeBgColor:
      - "#363a4f" # Surface0
    cherryPickedCommitBgColor:
      - "#8bd5ca" # Teal
    cherryPickedCommitFgColor:
      - "#8aadf4" # Blue
    unstagedChangesColor:
      - red # Red
customCommands:
  - key: 'C'
    context: 'global'
    command: "git commit"
    output: terminal
  - key: "<c-w>"
    context: "global"
    description: "Create worktree ../{project-folder}_{branch}"
    command: "git worktree add ./.worktrees/$(echo '{{.Form.Branch}}'| tr '/' '-') {{.Form.Branch}} && tmux new-window -c ./.worktrees/$(echo '{{.Form.Branch}}'| tr '/' '-')"
    prompts:
      - type: 'input'
        title: 'Which branch?'
        key: 'Branch'
        suggestions:
          command: > 
            git branch -a | sed -e 's/^.\sremotes\///' 
      - type: "confirm"
        title: "Create worktree?"
        body: "Create worktree at ./.worktrees for branch {{.Form.Branch}}?"
